services:
  - type: web
    name: subsidy-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn subsidy_api:app"
    envVars:
      - key: FLASK_ENV
        value: production
