services:
  - type: web
    name: subsidy-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python Subsidy_api.py"
    envVars:
      - key: FLASK_ENV
        value: production
